server:
  port: 19093

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/msaTest
    username: sa
    password:
    driver-class-name: org.h2.Driver

  cloud:
    loadbalancer:
#      ribbon:
#        enabled: false
      services:
        product-service:
          instances:
            - url: http://localhost:19093
              weight: 100
            - url: http://localhost:19094
              weight: 1

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0